### ISSUE TITLE
Solidity verifyProof function as view

### ISSUE THREAD

**Issue by dibi91** [privacy-scaling-explorations/halo2-solidity-verifier#18]
Hello,
would like to know if there is a reason behind not marking the verifyProof function on the Halo2Verifier as a view, as it does not write anything on storage.
Some ethereum libraries (like ethers js) relies on ABI specification and force to have signer to call that function (using smart contracts interfaces).
If there is no specific reason, I would like fix it.
Thank you!

**Comment by han0110** [comment]
Hi, mainly because there are 2 mode of verifier generation, one is verifier with vk hardcoded, the other is verifier with vk deployed separately and `vkAddress` is only known when calling the `verifyProof`. Tho the former doesn't need to have access to storage, but the latter will need.

So a fix is to make the function visibility as `view` if the mode is not separate, and as `public` as is if the mode is separate. Feel free to submit a PR to fix this, and thanks for pointing this out!

**Comment by dibi91** [comment]
Hi, thanks for the explanation, but I think that `view` visibility is doable in both ways; the verifier key, if deployed separately, is  stored inside `Halo2VerifyingKey`, the verifier got the key address as a function parameter ad read key from `Halo2VerifyingKey` storage, so no storage is written.
Another solution is to store `Halo2VerifyingKey` address during Verifier deployment, so the functions, in both cases, will share the same signature.

**Comment by han0110** [comment]
Ah you are right, I was confused by `pure` and `view`, we should be able to use `view` for both.

**Comment by dibi91** [comment]
Are there any additional setups I have to made for running tests or examples? I cannot run them, it always fails with this stack:
```
Verifier creation code size: 3684
thread 'main' panicked at library/core/src/panicking.rs:219:5:
unsafe precondition(s) violated: slice::get_unchecked_mut requires that the index is within the slice
stack backtrace:
   0: rust_begin_unwind
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_nounwind_fmt::runtime
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:110:18
   2: core::panicking::panic_nounwind_fmt
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:120:5
   3: core::panicking::panic_nounwind
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:219:5
   4: <usize as core::slice::index::SliceIndex<[T]>>::get_unchecked_mut::precondition_check
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/ub_checks.rs:68:21
   5: <usize as core::slice::index::SliceIndex<[T]>>::get_unchecked_mut
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/ub_checks.rs:75:17
   6: core::slice::<impl [T]>::get_unchecked_mut
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/slice/mod.rs:728:24
   7: revm_interpreter::interpreter::stack::Stack::dup
             at /home/pdibitonto/.cargo/registry/src/index.crates.io-6f17d22bba15001f/revm-interpreter-1.3.0/src/interpreter/stack.rs:206:18
   8: revm_interpreter::instructions::stack::dup
             at /home/pdibitonto/.cargo/registry/src/index.crates.io-6f17d22bba15001f/revm-interpreter-1.3.0/src/instructions/stack.rs:42:26
   9: revm_interpreter::instructions::opcode::eval
             at /home/pdibitonto/.cargo/registry/src/index.crates.io-6f17d22bba15001f/revm-interpreter-1.3.0/src/instructions/opcode.rs:68:13
  10: revm_interpreter::interpreter::Interpreter::step
             at /home/pdibitonto/.cargo/registry/src/index.crates.io-6f17d22bba15001f/revm-interpreter-1.3.0/src/interpreter.rs:138:9
  11: revm_interpreter::interpreter::Interpreter::run
             at /home/pdibitonto/.cargo/registry/src/index.crates.io-6f17d22bba15001f/revm-interpreter-1.3.0/src/interpreter.rs:144:13
  12: revm::evm_impl::EVMImpl<GSPEC,DB,_>::run_interpreter
             at /home/pdibitonto/.cargo/registry/src/index.crates.io-6f17d22bba15001f/revm-3.5.0/src/evm_impl.rs:660:13
  13: revm::evm_impl::EVMImpl<GSPEC,DB,_>::create_inner
             at /home/pdibitonto/.cargo/registry/src/index.crates.io-6f17d22bba15001f/revm-3.5.0/src/evm_impl.rs:537:13
  14: <revm::evm_impl::EVMImpl<GSPEC,DB,_> as revm_interpreter::host::Host>::create
             at /home/pdibitonto/.cargo/registry/src/index.crates.io-6f17d22bba15001f/revm-3.5.0/src/evm_impl.rs:961:19
  15: <revm::evm_impl::EVMImpl<GSPEC,DB,_> as revm::evm_impl::Transact<<DB as revm_primitives::db::Database>::Error>>::transact_preverified
             at /home/pdibitonto/.cargo/registry/src/index.crates.io-6f17d22bba15001f/revm-3.5.0/src/evm_impl.rs:315:55
  16: revm::evm_impl::Transact::transact::{{closure}}
             at /home/pdibitonto/.cargo/registry/src/index.crates.io-6f17d22bba15001f/revm-3.5.0/src/evm_impl.rs:79:27
  17: core::result::Result<T,E>::and_then
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/result.rs:1346:22
  18: revm::evm_impl::Transact::transact
             at /home/pdibitonto/.cargo/registry/src/index.crates.io-6f17d22bba15001f/revm-3.5.0/src/evm_impl.rs:78:9
  19: revm::evm::EVM<DB>::transact
             at /home/pdibitonto/.cargo/registry/src/index.crates.io-6f17d22bba15001f/revm-3.5.0/src/evm.rs:99:13
  20: revm::evm::EVM<DB>::transact_commit
             at /home/pdibitonto/.cargo/registry/src/index.crates.io-6f17d22bba15001f/revm-3.5.0/src/evm.rs:60:48
  21: halo2_solidity_verifier::evm::test::Evm::transact_success_or_panic
             at ./src/evm.rs:186:26
  22: halo2_solidity_verifier::evm::test::Evm::create
             at ./src/evm.rs:154:31
  23: separately::main
             at ./examples/separately.rs:26:28
  24: core::ops::function::FnOnce::call_once
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread caused non-unwinding panic. aborting.
[1]    896637 IOT instruction (core dumped)  RUST_BACKTRACE=1 cargo run --example separately --features=evm
```

**Comment by dibi91** [comment]
I've done some checks, the problem relies on rust milestone 1.78.0 (https://github.com/rust-lang/rust/issues/123285) and the Revm crates that use "get_unchecked_mut".
Locally, overriding cargo version to 1.77.0, all tests and example works well.
